language: node_js
node_js:
  - "5.6.0"
  - "5.5.0"
  - "4.3.1"
before_install:
  - sudo apt-get install -y libfuzzy-dev
  - npm install coffee-coverage istanbul coveralls
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - rm -rf ./coverage
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
